### ISSUE TITLE
Scheduled-based Python function for social media reporting

### ISSUE THREAD

**Issue by gbowerman** [Azure/ServerlessLibrary#102]
- Title: Scheduled-based Python function for social media reporting
________

- Description: Python function designed to run a daily Twitter search and send output to a Microsoft Teams channel
________

- Template: n/a - Full template support is not available for Azure Python Functions yet.
________

- Repository: https://github.com/gbowerman/twitter-code/tree/master/azurefunctions/dailyreport
________

- Language (optional): Python
________

- Technology (optional): Function App
________

- Solution Area (optional): Social media reporting
________

**Comment by asavaritayal** [comment]
@ColbyTresness please consider Guy's sample for the Serverless Hackfest challenge. 

/cc jeffhollan
