### ISSUE TITLE
Add PowerShell to supported languages

### ISSUE THREAD

**Issue by joeyaiello** [Azure/ServerlessLibrary#167]
There aren't any PowerShell samples in the Serverless library yet, but at some point it will need to be added (I'm about to reference it in my PowerShell Summit session tomorrow). 

Not sure if it's required to be added somewhere in the backend, but it looks like the UI change is pretty easy ([here](https://github.com/Azure/ServerlessLibrary/blob/6d9dc1341d4579d9bcd7ddb9db1124338bece1b4/ServerlessLibraryUI/src/components/AppTopbar.vue#L28) and [here](https://github.com/Azure/ServerlessLibrary/blob/016b30f628452fe1d99ded6200318d0edfa0a4dc/ServerlessLibraryUI/src/components/AppItem.vue#L96)). 

If that's all that needs to be done, I'm happy to submit the PR myself. Just need an ack that this is the right thing to do. Thanks!

**Comment by ColbyTresness** [comment]
Wait like 24 hours :)
