### ISSUE TITLE
No longer a contributer :-(

### ISSUE THREAD

**Issue by jefking** [Azure/ServerlessLibrary#30]
Bummer to kill the person who created this… Lame.

removed from commit history, as well as all references in humans.txt, site pages etc.

It was community run. Now... :-(

**Comment by fashaikh** [comment]
Working on this.  Will merge the history using these tools and figure out what else is needed.

https://thoughts.t37.net/merging-2-different-git-repositories-without-losing-your-history-de7a06bba804
