### ISSUE TITLE
Azure Sandbox Utils

### ISSUE THREAD

**Issue by wilfriedwoivre** [Azure/ServerlessLibrary#34]
Hello,
this is an issue that matches my Pull Request on master [Azure Sandbox Utils](https://github.com/Azure/ServerlessLibrary/commit/2c68a2f0c4b255b2ab2f3310f2c9e8cd698effef)

- Title: Azure Sandbox utils
________

- Description: Provide API to create temporary Resource Group. Provide function to remove temporary resource group each day
________

- Template: https://raw.githubusercontent.com/wilfriedwoivre/azure-sandbox-function/master/azuredeploy.json
________

- Repository: https://github.com/wilfriedwoivre/azure-sandbox-function
________

- Language (optional): csharp
________

- Technology (optional): Function App
________

- Solution Area (optional): Dev/Test
________

**Comment by fashaikh** [comment]
@wilfriedwoivre  Its live now! 
 sorry about the delay
![image](https://user-images.githubusercontent.com/2650941/46835881-49009a00-cd64-11e8-98cf-068ffc2ada36.png)
