### ISSUE TITLE
Change default to Master Branch

### ISSUE THREAD

**Issue by justinyoo** [Azure/ServerlessLibrary#35]
Hi, Team.

When I looked at the website, it apparently uses the `master` branch. However, the default branch is `v2`. I've got something to send PR, but in which branch should I send it?

**Comment by ColbyTresness** [comment]
Use V2! Leaving this open as the action item should be to make things clearer.

**Comment by fashaikh** [comment]
Should we update the "HOW TO CONTRIBUTE" link to https://github.com/Azure/ServerlessLibrary/blob/v2/README.md  for starters ?

**Comment by ColbyTresness** [comment]
This actually changed. @fashaikh please make default master, and close.

**Comment by ColbyTresness** [comment]
This is complete
