### ISSUE TITLE
Deep linking

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/ServerlessLibrary#41]
Should accept URL linking to different sets of templates.

**Comment by ColbyTresness** [comment]
@btardif opinions on how exactly we should do this?

**Comment by btardif** [comment]
the way I would do it is through query string parameters.

There are 2 scenarios:

- Deep linking to a search where query strings parameters representing each of the filters applied to the search.

One extra wrinkle here is if you need to include paging of results, the paging information should be included as part of the parameters as well.

- Deep linking a specific template where query string parameter represents a unique template.

**Comment by ColbyTresness** [comment]
This will be deployed today.
