### ISSUE TITLE
ARM Template Generated link broken

### ISSUE THREAD

**Issue by nastassiar** [Azure/ServerlessLibrary#44]
There ARM Template generator link just goes to the library

**Comment by ColbyTresness** [comment]
Known issue that will hopefully be fixed within a week or two

**Comment by ColbyTresness** [comment]
This is now fixed

**Comment by jefking** [comment]
Link exists in the bottom of the readme file.

**Comment by ColbyTresness** [comment]
Any reason you reopened this? Thought it was fixed

**Comment by ColbyTresness** [comment]
Closing again since this is fixed.
