### ISSUE TITLE
ARM Deployment History Cleaner

### ISSUE THREAD

**Issue by justinyoo** [Azure/ServerlessLibrary#58]
Hi, Team.

I'd like to submit my **awesome** Logic App that I introduced during my [MS Ignite talk](https://myignite.techcommunity.microsoft.com/sessions/67356).

- Title: ARM Deployment History Cleaner
________

- Description: This provides Azure Logic Apps to clean up ARM deployment history before hitting 800 limits.
________

- Template: https://raw.githubusercontent.com/aliencube/ARM-Deployment-History-Cleaner/master/azuredeploy.json
________

- Repository: https://github.com/aliencube/ARM-Deployment-History-Cleaner
________

- Language (optional): N/A
________

- Technology (optional): Logic App
________

- Solution Area (optional): Azure DevOps
________

**Comment by fashaikh** [comment]
This is  live now. Thanks for your  contribution!
