### ISSUE TITLE
Key Vault Custom Connector for Logic App

### ISSUE THREAD

**Issue by justinyoo** [Azure/ServerlessLibrary#59]
Hi, Team.

I'd like to add my **awesome** Function App as a Logic App custom connector to Key Vault.

- Title: Key Vault Custom Connector for Logic App
________

- Description: This provides a custom Key Vault API Connector for Logic Apps.
________

- Template: https://raw.githubusercontent.com/aliencube/Key-Vault-Connector-for-Logic-Apps/dev/azuredeploy.json
________

- Repository: https://github.com/aliencube/Key-Vault-Connector-for-Logic-Apps
________

- Language (optional): C#
________

- Technology (optional): Function App
________

- Solution Area (optional): Azure DevOps, Integration, Identity
________

**Comment by fashaikh** [comment]
This is  live now. Thanks for your  contribution!
