### ISSUE TITLE
https://www.serverlesslibrary.net gives NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by mi-hol** [Azure/ServerlessLibrary#60]
Your connection is not private
Attackers might be trying to steal your information from www.serverlesslibrary.net (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID

**Comment by fashaikh** [comment]
What browser / version are you seeing this in. I checked with the latest chrome and edge and don't see that.

![image](https://user-images.githubusercontent.com/2650941/49534376-34c5ae80-f876-11e8-8a90-b6f0ea24e610.png)

If you are still seeing it could you get  a timestamp and screenshot of the certificate being served like this 
![image](https://user-images.githubusercontent.com/2650941/49534437-5fb00280-f876-11e8-8a65-df4e92c08eed.png)

**Comment by mi-hol** [comment]
Chrome Version 70.0.3538.110 (Official Build) (64-bit)
but doesn't appear today
