### ISSUE TITLE
Request to add Start/Stop VM App

### ISSUE THREAD

**Issue by anirudhgarg** [Azure/ServerlessLibrary#61]
If you'd like to submit a Repo to the Azure Serverless Community Library, fill out the following template:

- Title:
 Start/Stop Azure VM with ResourceGroup and Tag filtering.

- Description: A short block of text (~100 characters max) explaining what your sample does.
This solution allows you to Start and Stop Azure VM's for a given Subscription, Resource Group or Tags based on a schedule.
The implementation uses Azure VM async API's and hence potentially hundreds of VM's can be started/stopped.

- Template: The path to the ARM template which deploys the application. For more information, see the [README](https://github.com/Azure/FunctionLibrary/blob/master/README.md).

https://github.com/anirudhgarg/functions-logicapp-startstopvms/blob/master/azuredeploy.json

- Repository: The URL of a public git repository.
https://github.com/anirudhgarg/functions-logicapp-startstopvms

- Language (optional): The language your code is written in (Functions only.)
C#

- Technology (optional): Whether your app is a Function App or a Logic App
Function and  Logic App

- Solution Area (optional): A broad level categorization of what type of solution you've built (IoT, ML, Data Processing, ...)
IT, Azure Management

**Comment by fashaikh** [comment]
Im tagging this as a logic app, for now. We could  create two entries , one for functionapp and another for logic app if needed. 
But longer term we need to figure out the best way to tag solutions like these

**Comment by fashaikh** [comment]
Its live right now

**Comment by anirudhgarg** [comment]
Thanks I am ok to tag this as Logic App for now.

**Comment by ColbyTresness** [comment]
Note that in the future we hope to have a different category for "end to end solution" or something like that, but don't support today. Eventually we can move this to that category.

**Comment by anirudhgarg** [comment]
Sorry I had the wrong URL for the ARM template it should be what I have below. I would appreciate it if you could update it. 

https://raw.githubusercontent.com/anirudhgarg/functions-logicapp-startstopvms/master/azuredeploy.json

**Comment by fashaikh** [comment]
Updated. I
