### ISSUE TITLE
Live stream Age and Emotion Function

### ISSUE THREAD

**Issue by JimPaine** [Azure/ServerlessLibrary#62]
Hi All,

It would be great to get my live streaming face api demo included in the library, all fronted by Functions :) also includes the new @Microsoft.KeyVault app settings

- Title: Live stream Age and Emotion
________

- Description: A HTML5 page which streams your camera to the Face API for age and emotion, all via a V2 function
________

- Template: https://github.com/JimPaine/emotion-checker/blob/master/azuredeploy.json
________

- Repository: https://github.com/JimPaine/emotion-checker
________

- Language (optional): C#
________

- Technology (optional): Function App
________

- Solution Area (optional): Azure Functions v2, Cognitive Services, Face API, Key Vault, .NET Core
________

**Comment by fashaikh** [comment]
This is live now. Thank you for your contirbution @JimPaine !
