### ISSUE TITLE
@Microsoft.KeyVault appsetting examples for C# and node

### ISSUE THREAD

**Issue by JimPaine** [Azure/ServerlessLibrary#63]
- Title: Simplified KeyVault integration with @Microsoft.KeyVault
________

- Description: A demo showing how to use @Microsoft.KeyVault in appsettings for simplified secret management
________

- Template: https://github.com/JimPaine/Azure-Functions-KeyVault-Demo/blob/master/azuredeploy.json
________

- Repository: https://github.com/JimPaine/Azure-Functions-KeyVault-Demo
________

- Language (optional): C# and JavaScript
________

- Technology (optional): FunctionApp
________

- Solution Area (optional): KeyVault, Managed Service Identity
________

**Comment by fashaikh** [comment]
This is live now. Thank you for your contirbution @JimPaine !
