### ISSUE TITLE
New Repo: Remove metadata with Azure Functions

### ISSUE THREAD

**Issue by 0GiS0** [Azure/ServerlessLibrary#78]
If you'd like to submit a Repo to the Azure Serverless Community Library, fill out the following template:

- Title: Remove metadata with Azure Functions
________

- Description: It removes file metadata using Azure Functions.
________

- Template: https://github.com/0GiS0/azure-function-clean-exif/blob/master/azure.deploy.json
________

- Repository: https://github.com/0GiS0/azure-function-clean-exif
________

- Language (optional): JavaScript
________

- Technology (optional): Function App
________

- Solution Area (optional): 
________

**Comment by fashaikh** [comment]
Live now. Thanks for your contribution !
