### ISSUE TITLE
New Repo: Audio utilities using Azure Functions

### ISSUE THREAD

**Issue by 0GiS0** [Azure/ServerlessLibrary#79]
If you'd like to submit a Repo to the Azure Serverless Community Library, fill out the following template:

- Title: Audio utilities using Azure Functions.
________

- Description: Conversions using ffmpeg and transcriptions with Speech Service:

* Mp3ToWav: It converts from MP3 to WAV in order to be treated by Speech service from Cognitive Services, but it can be used simply as a transformation method. 
* WavToText: Use Speech Service to get the audio transcript.

________

- Template: https://github.com/0GiS0/audio-azure-functions/blob/master/azure.deploy.json
________

- Repository: https://github.com/0GiS0/audio-azure-functions
________

- Language (optional): C#
________

- Technology (optional): Function App
________

- Solution Area (optional): -
________

**Comment by fashaikh** [comment]
Live now. Thanks for your contribution !
