### ISSUE TITLE
Request for Addition to ServerlessLibrary.net

### ISSUE THREAD

**Issue by raahmed** [Azure/ServerlessLibrary#90]
- Title: Read Excel From Blob Storage, Process and Add to Azure Queue.

Please Note: The user will have to edit this code to make it work by following the directions in the README.
________

- Description: This application takes a specific type of csv file (detailed in the project README), cleans the data and then places the contents in .json format into a Queue.
________

- Template: https://github.com/raahmed/BlobStorageTrigger/blob/master/azuredeploy.json

- Repository: https://github.com/raahmed/BlobStorageTrigger/blob/master/azuredeploy.json
________

- Language (optional): Python
________

- Technology (optional): Function App
________

- Solution Area (optional): Data Processing.
________

**Comment by raahmed** [comment]
Abandoning and re-creating in future.

**Comment by fashaikh** [comment]
https://github.com/raahmed/BlobStorageTrigger/blob/master/azuredeploy.json is empty 
Could you update it so people can deploy right away

**Comment by raahmed** [comment]
Hi

I clicked the link below and it definitely has content…

[cid:image001.jpg@01D4B96F.82E4FB20]

**Comment by raahmed** [comment]
No worries – I updated that just now

https://github.com/raahmed/QueueStorageTrigger/blob/master/azuredeploy.json

Looks like I forgot to push the template 😊
