### ISSUE TITLE
New Repo: Serverless endpoint reading data from Azure CosmosDB 

### ISSUE THREAD

**Issue by simonaco** [Azure/ServerlessLibrary#96]
If you'd like to submit a Repo to the Azure Serverless Community Library, fill out the following template:

- Title: Build a serverless API with Node.js on top of Azure Functions and Azure Cosmos DB
________

- Description: A short block of text (~100 characters max) explaining what your sample does.
________

- Template: https://raw.githubusercontent.com/simonaco/nodebinar/master/azuredeploy.json 
________

- Repository: https://github.com/simonaco/nodebinar
________

- Language (optional): Javascript
________

- Technology (optional): Whether your app is a Function App or a Logic App
________

- Solution Area (optional): A broad level categorization of what type of solution you've built (IoT, ML, Data Processing, ...)
________

**Comment by fashaikh** [comment]
its live for a week or so now. Forgot to close it . sorry about the delay, and thanks for your contribution !
